name: DataGuard SG
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.11, 3.12]
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v5
                with:
                    python-version: ${{ matrix.python-version }}

            -   name: Install dependencies
                run: pip install -e ".[dev]"
            
            -   name: Black check
                run: black --check --target-version py311 --target-version py312 src/ tests/
            
            -   name: flake8 check
                run: flake8 src/ tests/
            
            -   name: mypy check
                run: mypy src/ --explicit-package-bases

            -   name: Run tests
                run: pytest -v --cov=src --cov-report=term-missing